name: Repjegy Figyelo

on:
  schedule:
    - cron: '0 6,18 * * *'   # 6:00 és 18:00 UTC (nyáron 8:00 és 20:00 Magyarországon)
  workflow_dispatch:         # manuális indítás lehetősége a GitHub felületén

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and Run Script
        timeout-minutes: 4      # Biztonsági időkorlát, hogy ne fusson 19 percig
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          pip install playwright requests
          playwright install chromium
          python repjegy_figyelo.py
